def importSubsets ():
    #lasso subsets
    lasso_subset_0 = ['revenue',
    'costOfRevenue',
    'otherExpenses',
    'interestIncome',
    'weightedAverageShsOut',
    'cashAndShortTermInvestments',
    'otherCurrentAssets',
    'totalCurrentAssets',
    'goodwill',
    'intangibleAssets',
    'longTermInvestments',
    'otherAssets',
    'deferredRevenue',
    'otherCurrentLiabilities',
    'deferredRevenueNonCurrent',
    'totalNonCurrentLiabilities',
    'capitalLeaseObligations',
    'preferredStock',
    'totalInvestments',
    'netIncome_cf',
    'depreciationAndAmortization_cf',
    'deferredIncomeTax',
    'stockBasedCompensation',
    'inventory_cf',
    'netCashProvidedByOperatingActivities',
    'salesMaturitiesOfInvestments',
    'otherFinancingActivites',
    'effectOfForexChangesOnCash',
    'daysOfPayablesOutstanding',
    'netProfitMargin',
    'freeCashFlowPerShare',
    'capitalExpenditureCoverageRatio',
    'priceEarningsRatio',
    'close',
    'totalDividend',
    'operatingIncome_TTM',
    'eps_TTM',
    'YoY_ebitda',
    'YoY_operatingIncome',
    'YoY_eps']
    lasso_ubset_15 =  ['revenue',
    'costOfRevenue',
    'generalAndAdministrativeExpenses',
    'sellingAndMarketingExpenses',
    'interestIncome',
    'operatingIncome',
    'weightedAverageShsOut',
    'cashAndShortTermInvestments',
    'otherCurrentAssets',
    'totalCurrentAssets',
    'goodwill',
    'taxAssets',
    'totalAssets',
    'accountPayables',
    'longTermDebt',
    'deferredRevenueNonCurrent',
    'deferredTaxLiabilitiesNonCurrent',
    'capitalLeaseObligations',
    'commonStock',
    'netIncome_cf',
    'depreciationAndAmortization_cf',
    'deferredIncomeTax',
    'commonStockIssued',
    'effectOfForexChangesOnCash',
    'freeCashFlow',
    'daysOfInventoryOutstanding',
    'daysOfPayablesOutstanding',
    'companyEquityMultiplier',
    'operatingCashFlowPerShare',
    'capitalExpenditureCoverageRatio',
    'priceEarningsRatio',
    'priceEarningsToGrowthRatio',
    'close',
    'totalDividend',
    'researchAndDevelopmentExpenses_TTM',
    'YoY_netIncome']

    #mi subsets
    mi_subset_0 =  ['numberOfShares',
    'costOfRevenue_TTM',
    'QoQ_costAndExpenses',
    'incomeBeforeTaxRatio',
    'goodwillAndIntangibleAssets',
    'earnings',
    'accountsPayables',
    'fixedAssetTurnover',
    'excessReturn_84',
    'netIncome_bin',
    'ebtPerEbit',
    'netIncome_cf',
    'YoY_netIncome',
    'totalOtherIncomeExpensesNet',
    'Volatility_42',
    'operatingIncome',
    'dividendPayoutRatio',
    'cashAtEndOfPeriod',
    'depreciationAndAmortization',
    'cashFlowCoverageRatios',
    'purchasesOfInvestments',
    'assetTurnover',
    'eps',
    'commonStock']
    mi_subset_15 = ['Volatility_84','Volatility_21','operatingIncome','costAndExpenses_TTM','netIncome_bin',
    'dividendPayoutRatio',
    'totalDividend',
    'dividend',
    'netIncome_TTM',
    'dividendsPaid',
    'otherCurrentLiabilities',
    'dividendYield',
    'totalAssets',
    'eps_TTM',
    'otherNonCurrentAssets',
    'totalLiabilitiesAndTotalEquity',
    'otherCurrentAssets',
    'marketcap_bin',
    'netCashUsedForInvestingActivites',
    'goodwill',
    'totalNonCurrentAssets']

    
    #subsets from light gbm
    lgb_subset = ['Volatility_84', 'close', 'MA_21', 'Volatility_21', 'YoY_revenue',
        'priceEarningsRatio', 'priceToSalesRatio', 'Volatility_42', 'goodwill',
        'retainedEarnings', 'Volatility_63', 'QoQ_ebitda',
        'otherInvestingActivites', 'excessReturn_21',
        'accumulatedOtherComprehensiveIncomeLoss', 'priceEarningsToGrowthRatio',
        'othertotalStockholdersEquity', 'MA_84', 'payoutRatio',
        'accountsPayables']

    #correlation bases subsets
    corr_subset0 = ['Volatility_63', 'Volatility_42', 'Volatility_84', 'Volatility_21',
        'close', 'netProfitMargin_bin', 'netIncome_bin', 'priceToSalesRatio',
        'priceSalesRatio', 'capitalExpenditureCoverageRatio',
        'sector_priceEarningsRatio_bin', 'industry_Biotechnology',
        'excessReturn_42', 'currentRatio', 'industry_Electronic Components',
        'returnOnCapitalEmployed', 'operatingCashFlowSalesRatio',
        'netCashProvidedByOperatingActivities', 'operatingCashFlow',
        'pretaxProfitMargin', 'incomeBeforeTaxRatio', 'ebitPerRevenue',
        'operatingProfitMargin', 'operatingIncomeRatio', 'netIncomeRatio',
        'netProfitMargin', 'eps', 'epsdiluted', 'returnOnEquity']

    corr_subset15 = ['close', 'dividend', 'totalAssets', 'eps_TTM', 'dividendYield',
        'netIncome_TTM', 'earnings_TTM', 'totalDividend', 'ebitda_TTM',
        'dividendPayoutRatio', 'mktcap', 'payoutRatio', 'ebit',
        'retainedEarnings', 'netIncome_cf', 'daysOfInventoryOutstanding',
        'grossProfitMargin', 'fixedAssetTurnover', 'daysOfPayablesOutstanding',
        'payablesTurnover', 'dividendsPaid', 'marketcap_bin', 'assetTurnover',
        'sector_priceEarningsRatio_bin', 'netProfitMargin_bin', 'netIncome_bin',
        'Volatility_21', 'Volatility_42', 'Volatility_63']
    
    return(lasso_subset_0, lasso_ubset_15, mi_subset_0, mi_subset_15, lgb_subset, corr_subset0, corr_subset15)